name: master

on:
  push:
    branches: 
      - master

jobs:
  github-page:
    name: GitHub Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build Storybook
        run: npm run storybook:build
      - name: Commit Storybook Files
        run: |
          git config --local user.email "botmcbotface26@gmail.com"
          git config --local user.name "Bot McBotface" 
          git commit -m "Publishing Storybook" -a
      - name: Deploy Storybook 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test:coverage
      - name: Build Formbuilder
        run: npm run build
      - name: Archive Formbuilder Artifact
        uses: actions/upload-artifact@master
        with: 
          name: build
          path: build
  deploy: 
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Storybook Artifact
        uses: actions/download-artifact@master
        with:
          name: docs
      - name: Download Formbuilder Artifact
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
