name: pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test:coverage
      - name: Build
        run: npm run build
      - name: workaround for detached HEAD
        run: |
          echo ${GITHUB_HEAD_REF#refs/heads/} && git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull
      - name: Image Regression Test
        run: npm run test:image-regression
