name: pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        run: |
            git fetch --prune --unshallow
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test:coverage
      - name: Build
        run: npm run build
      - name: Image Regression Test
        run: npm run test:image-regression && ls
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EXPECTED_KEY: ${{ github.base_ref }}
          ACTUAL_KEY: ${{ github.head_ref }}
